name = "OarClusterManager"
uuid = "207ec4d0-90e1-11e9-024b-2589a7dd4862"
authors = ["Gilles <gilles.bareilles@gmail.com>"]
version = "0.1.0"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
